#!/usr/bin/env python3
"""Generate cross-platform launcher scripts for skills that share helper scripts.

The canonical helper scripts live once in ``plugins/research-papers/scripts/``.
Each skill that invokes one needs it available as ``scripts/<name>.py`` inside
the skill directory. That used to be done with git symlinks pointing at
``../../../scripts/<name>.py`` -- but on Windows git defaults to
``core.symlinks=false`` and materializes those symlinks as tiny text
placeholders, so ``uv run scripts/<name>.py`` executes the placeholder and
fails.

Instead, each skill gets a small generated *launcher* at
``skills/<skill>/scripts/<name>.py`` that carries the canonical script's PEP 723
metadata (so ``uv run`` provisions the right environment) and executes the
single canonical implementation via :mod:`runpy`, located relative to its own
``__file__``. This works on Windows/macOS/Linux and from any clone location,
with no symlinks and no duplicated logic.

Run::

    python tools/sync_skill_launchers.py
"""

from __future__ import annotations

from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = PLUGIN_ROOT / "scripts"
SKILLS_DIR = PLUGIN_ROOT / "skills"

# Canonical scripts each skill invokes and therefore needs a launcher for.
# _paper_id.py is intentionally absent: it is import-only and resolves from the
# canonical scripts dir when a canonical script runs (its __file__ is canonical),
# so no per-skill copy is needed.
MANIFEST = {
    "paper-reader": ["paper_hash.py", "build_keymap.py", "render_pages.py", "pdf_adoption.py"],
    "paper-retriever": ["fetch_paper.py", "search_papers.py"],
    "process-leads": ["get_citations.py", "paper_hash.py"],
    "verify-citations": ["verify_citations.py"],
    "process-new-papers": ["pdf_adoption.py", "lint_paper_schema.py"],
    "ingest-new-papers": ["lint_paper_schema.py"],
    "ingest-collection": ["lint_paper_schema.py"],
    "lint-paper": ["lint_paper_schema.py"],
}

# Per-skill files that the old symlink layout created but the launcher layout no
# longer needs. Removed during sync.
OBSOLETE = {
    "paper-reader": ["_paper_id.py"],
    "paper-retriever": ["_paper_id.py"],
    "process-leads": ["_paper_id.py"],
}

PEP723_START = "# /// script"
PEP723_END = "# ///"

_LAUNCHER_BODY = (
    "import runpy\n"
    "import sys\n"
    "from pathlib import Path\n"
    "\n"
    '_target = Path(__file__).resolve().parents[3] / "scripts" / Path(__file__).name\n'
    "sys.argv[0] = str(_target)\n"
    'runpy.run_path(str(_target), run_name="__main__")\n'
)


def extract_pep723(text: str) -> str | None:
    """Return the verbatim PEP 723 inline-metadata block, or None if absent."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip() == PEP723_START:
            start = i
            break
    if start is None:
        return None
    for j in range(start + 1, len(lines)):
        if lines[j].strip() == PEP723_END:
            return "\n".join(lines[start : j + 1])
    return None


def render_launcher(canonical_path: Path) -> str:
    """Render the launcher source for a given canonical script."""
    name = canonical_path.name
    block = extract_pep723(canonical_path.read_text(encoding="utf-8"))
    docstring = (
        '"""Generated by tools/sync_skill_launchers.py. DO NOT EDIT.\n'
        "\n"
        "Cross-platform launcher: runs the single canonical implementation in\n"
        f"plugins/research-papers/scripts/{name} via runpy, located relative to\n"
        "this file. Works on Windows/macOS/Linux and from any clone location,\n"
        "without symlinks or duplicated logic. Regenerate with:\n"
        "    python tools/sync_skill_launchers.py\n"
        '"""'
    )
    parts = ["#!/usr/bin/env python3"]
    if block:
        parts.append(block)
    parts.append(docstring)
    parts.append(_LAUNCHER_BODY)
    return "\n".join(parts)


def sync() -> list[Path]:
    """Write all launchers and remove obsolete per-skill copies. Returns written paths."""
    written: list[Path] = []
    for skill, names in MANIFEST.items():
        dest_dir = SKILLS_DIR / skill / "scripts"
        dest_dir.mkdir(parents=True, exist_ok=True)
        for name in names:
            canonical = SCRIPTS_DIR / name
            if not canonical.exists():
                raise FileNotFoundError(f"canonical script missing: {canonical}")
            dest = dest_dir / name
            dest.write_text(render_launcher(canonical), encoding="utf-8", newline="\n")
            written.append(dest)
    for skill, names in OBSOLETE.items():
        for name in names:
            stale = SKILLS_DIR / skill / "scripts" / name
            if stale.is_symlink() or stale.exists():
                stale.unlink()
    return written


if __name__ == "__main__":
    for path in sync():
        print(f"wrote {path.relative_to(PLUGIN_ROOT).as_posix()}")
