#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["arxiv>=2.1", "semanticscholar>=0.8", "requests>=2.28"]
# ///
"""Generated by tools/sync_skill_launchers.py. DO NOT EDIT.

Cross-platform launcher: runs the single canonical implementation in
plugins/research-papers/scripts/search_papers.py via runpy, located relative to
this file. Works on Windows/macOS/Linux and from any clone location,
without symlinks or duplicated logic. Regenerate with:
    python tools/sync_skill_launchers.py
"""
import runpy
import sys
from pathlib import Path

_target = Path(__file__).resolve().parents[3] / "scripts" / Path(__file__).name
sys.argv[0] = str(_target)
runpy.run_path(str(_target), run_name="__main__")
